### ISSUE TITLE
[DISCUSSION]: designsystem/ui を除くcoreパッケージについて

### ISSUE THREAD

**Issue by chippy-ao** [tatsutakein-jp/asis-app#5]
Widgetを使用しない部分のパッケージたちについて、現状はFlutterPackageでの作成となっていますが、DartPackageでも十分ではないかと考えています。

`dart create -t package <PACKAGE_NAME>`と`flutter create -t package <PACKAGE_NAME>`での差異を確認したところ、`pubspec.yaml`が以下のように違いました。

```yaml
name: dart_package
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.4

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
```

```yaml
name: flutter_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
```
単純に`flutter`に依存をしているかの有無で、１から作り直す必要があるわけではなさそうでした。
Flutterに依存してもどうせ使用しないと思うので、不要なものは消しちゃってもいいのかなと思いました。

---

余談
> [!TIP]
> `fvm dart [somthing]` と打つことで、`.fvm/flutter_sdk`にあるDartバージョンであれこれできることを今更知りました（普通に`dart [something]`と打つとbrew側を参照してしまいますが）。
> ちなみに`melos`については、プロジェクトルートにある`pubspec.yaml`のdependenciesのバージョンを使用することになるので、例えbrew側のdartのmelosがバージョンアップしていても、そこさえ変にいじらなければ、flutter/dart/melos 全てでプロジェクトごとに正しいものを使用可能です。
